DROP_TABLE = {
	["npc_arena_boss_freya"] = {
		hero = "npc_arena_hero_freya",
		{ Item = "item_soul_of_titan", DropChance = 30, DamageWeightPct = 30, },
		{ Item = "item_soul_of_titan", DropChance = 30, DamageWeightPct = 30, },
		{ Item = "item_dark_blade", DropChance = 50, DamageWeightPct = 25, },
		{ Item = "item_dark_blade", DropChance = 30, DamageWeightPct = 25, },
		{ Item = "item_phantom_bone", DropChance = 40, DamageWeightPct = 20, },
		{ Item = "item_moon_dust", DropChance = 50, DamageWeightPct = 25, },
		{ Item = "item_cursed_eye", DropChance = 30, DamageWeightPct = 50, },
		{ Item = "item_fallen_star", DropChance = 25,DamageWeightPct = 50,  },
		{ Item = "item_demons_paw", DropChance = 30, DamageWeightPct = 50, },
		{ Item = "item_demons_paw", DropChance = 30, DamageWeightPct = 50, },

		{ Item = "item_shard_primal_large", DropChance = 30, },
		{ Item = "item_shard_str_extreme", DropChance = 40, },
		{ Item = "item_shard_agi_extreme", DropChance = 40, },
		{ Item = "item_shard_int_extreme", DropChance = 40, },
	},
	["npc_arena_boss_zaken"] = {
		hero = "npc_arena_hero_zaken",
		{ Item = "item_soul_of_titan", DropChance = 30, DamageWeightPct = 30, },
		{ Item = "item_soul_of_titan", DropChance = 30, DamageWeightPct = 30, },
		{ Item = "item_dark_blade", DropChance = 50, DamageWeightPct = 25, },
		{ Item = "item_dark_blade", DropChance = 30, DamageWeightPct = 25, },
		{ Item = "item_phantom_bone", DropChance = 40, DamageWeightPct = 20, },
		{ Item = "item_moon_dust", DropChance = 50, DamageWeightPct = 25, },
		{ Item = "item_cursed_eye", DropChance = 30, DamageWeightPct = 50, },
		{ Item = "item_fallen_star", DropChance = 25, DamageWeightPct = 50, },
		{ Item = "item_demons_paw", DropChance = 30, DamageWeightPct = 50, },
		{ Item = "item_demons_paw", DropChance = 30, DamageWeightPct = 50, },

		{ Item = "item_shard_primal_large", DropChance = 30, },
		{ Item = "item_shard_str_extreme", DropChance = 40, },
		{ Item = "item_shard_agi_extreme", DropChance = 40, },
		{ Item = "item_shard_int_extreme", DropChance = 40, },
	},
	["npc_arena_boss_central"] = {
		{ Item = "item_soul_of_titan", DropChance = 30, DamageWeightPct = 30, },
		{ Item = "item_soul_of_titan", DropChance = 30, DamageWeightPct = 30, },
		{ Item = "item_dark_blade", DropChance = 50, DamageWeightPct = 25, },
		{ Item = "item_dark_blade", DropChance = 30, DamageWeightPct = 25, },
		{ Item = "item_phantom_bone", DropChance = 40, DamageWeightPct = 20, },
		{ Item = "item_moon_dust", DropChance = 50, DamageWeightPct = 25, },
		{ Item = "item_cursed_eye", DropChance = 30, DamageWeightPct = 50, },
		{ Item = "item_fallen_star", DropChance = 25, DamageWeightPct = 50, },
		{ Item = "item_demons_paw", DropChance = 30, DamageWeightPct = 50, },
		{ Item = "item_demons_paw", DropChance = 30, DamageWeightPct = 50, },

		{ Item = "item_shard_primal_large", DropChance = 30, },
		{ Item = "item_shard_str_extreme", DropChance = 40, },
		{ Item = "item_shard_agi_extreme", DropChance = 40, },
		{ Item = "item_shard_int_extreme", DropChance = 40, },
	},

	["npc_arena_boss_l1_v1"] = {
		{ Item = "item_dark_blade", DropChance = 20, DamageWeightPct = 25, },
		{ Item = "item_dark_blade", DropChance = 10, DamageWeightPct = 25, },
		{ Item = "item_phantom_bone", DropChance = 15, DamageWeightPct = 20, },
		{ Item = "item_moon_dust", DropChance = 20, DamageWeightPct = 25, },
		{ Item = "item_moon_dust", DropChance = 20, DamageWeightPct = 25, },
		{ Item = "item_cursed_eye", DropChance = 10, DamageWeightPct = 50, },
		{ Item = "item_fallen_star", DropChance = 10, DamageWeightPct = 50, },

		-- { Item = "item_soul_of_titan", DropChance = 15, DamageWeightPct = 30, },
		-- { Item = "item_demons_paw", DropChance = 14, DamageWeightPct = 50,  },
		--{ Item = "item_shard_primal_medium", DropChance = 30, },
		--{ Item = "item_shard_str_large", DropChance = 35, },
		--{ Item = "item_shard_agi_large", DropChance = 35, },
		--{ Item = "item_shard_int_large", DropChance = 35, },
	},
	["npc_arena_boss_l1_v2"] = {
		{ Item = "item_dark_blade", DropChance = 20, DamageWeightPct = 25, },
		{ Item = "item_dark_blade", DropChance = 10, DamageWeightPct = 25, },
		{ Item = "item_phantom_bone", DropChance = 15, DamageWeightPct = 20, },
		{ Item = "item_moon_dust", DropChance = 25, DamageWeightPct = 25, },
		{ Item = "item_moon_dust", DropChance = 25, DamageWeightPct = 25, },
		{ Item = "item_cursed_eye", DropChance = 10, DamageWeightPct = 50, },
		{ Item = "item_fallen_star", DropChance = 10, DamageWeightPct = 50, },

		-- { Item = "item_soul_of_titan", DropChance = 15, DamageWeightPct = 30, },
		-- { Item = "item_demons_paw", DropChance = 14, DamageWeightPct = 50, },
		--{ Item = "item_shard_primal_medium", DropChance = 30, },
		--{ Item = "item_shard_str_large", DropChance = 35, },
		--{ Item = "item_shard_agi_large", DropChance = 35, },
		--{ Item = "item_shard_int_large", DropChance = 35, },
	},
	["npc_arena_boss_l2_v1"] = {
		{ Item = "item_soul_of_titan", DropChance = 90, DamageWeightPct = 30, },
		{ Item = "item_dark_blade", DropChance = 40, DamageWeightPct = 25, },
		{ Item = "item_phantom_bone", DropChance = 35, DamageWeightPct = 20, },
		{ Item = "item_moon_dust", DropChance = 40, DamageWeightPct = 25, },
		{ Item = "item_soul_of_titan", DropChance = 25, DamageWeightPct = 30, },
		{ Item = "item_cursed_eye", DropChance = 20, DamageWeightPct = 50, },
		{ Item = "item_fallen_star", DropChance = 20, DamageWeightPct = 50, },
		{ Item = "item_demons_paw", DropChance = 90, DamageWeightPct = 50, },
		{ Item = "item_demons_paw", DropChance = 20, DamageWeightPct = 50, },

		{ Item = "item_shard_primal_medium", DropChance = 10, },
		{ Item = "item_shard_str_large", DropChance = 12, },
		{ Item = "item_shard_agi_large", DropChance = 12, },
		{ Item = "item_shard_int_large", DropChance = 12, },
		{ Item = "item_shard_primal_large", DropChance = 16, },
		{ Item = "item_shard_str_extreme", DropChance = 20, },
		{ Item = "item_shard_agi_extreme", DropChance = 20, },
		{ Item = "item_shard_int_extreme", DropChance = 20, },
	},
	["npc_arena_boss_l2_v2"] = {
		{ Item = "item_soul_of_titan", DropChance = 90, DamageWeightPct = 30, },
		{ Item = "item_dark_blade", DropChance = 40, DamageWeightPct = 25, },
		{ Item = "item_phantom_bone", DropChance = 35, DamageWeightPct = 20, },
		{ Item = "item_moon_dust", DropChance = 40, DamageWeightPct = 25, },
		{ Item = "item_soul_of_titan", DropChance = 25, DamageWeightPct = 30, },
		{ Item = "item_cursed_eye", DropChance = 20, DamageWeightPct = 50, },
		{ Item = "item_fallen_star", DropChance = 20, DamageWeightPct = 50, },
		{ Item = "item_demons_paw", DropChance = 90, DamageWeightPct = 50, },
		{ Item = "item_demons_paw", DropChance = 20, DamageWeightPct = 50, },

		{ Item = "item_shard_primal_medium", DropChance = 10, },
		{ Item = "item_shard_str_large", DropChance = 12, },
		{ Item = "item_shard_agi_large", DropChance = 12, },
		{ Item = "item_shard_int_large", DropChance = 12, },
		{ Item = "item_shard_primal_large", DropChance = 16, },
		{ Item = "item_shard_str_extreme", DropChance = 20, },
		{ Item = "item_shard_agi_extreme", DropChance = 20, },
		{ Item = "item_shard_int_extreme", DropChance = 20, },
	},
}
