MEEPO_SHARED_ITEMS = {
	item_boots = true,
	item_phase_boots = true,
	item_travel_boots = true,
	item_travel_boots_2 = true,
	item_tranquil_boots = true,
	item_arcane_boots = true,
	item_steam_footgear = true,
	item_power_treads = true,
	item_angel_wings = true,
	item_titanium_fruit = true,
	item_black_king_bar_arena = true,
	item_black_king_bar_2 = true,
	item_black_king_bar_3 = true,
	item_black_king_bar_4 = true,
	item_black_king_bar_5 = true,
	item_black_king_bar_6 = true,
	item_chest_of_midas = true,
	item_quelling_fury = true,

	item_refresher_core = true,
	item_elemental_fury = true,
	item_heavy_war_axe_of_rage_damage = true,
	item_heavy_war_axe_of_rage_health,
	item_sange_arena = true,
	item_sange_and_yasha_arena = true,
	item_nightshadow = true,
	item_nightshadow_and_sange = true,
	item_nightshadow_and_yasha = true,
	item_three_spirits_blades = true,
	item_monkey_king_bar = true,
	item_demon_king_bar = true,
}
