MEEPO_SHARED_ITEMS = {
	item_boots = true,
	item_phase_boots = true,
	item_travel_boots = true,
	item_travel_boots_2 = true,
	item_tranquil_boots = true,
	item_arcane_boots = true,
	item_steam_footgear = true,
	item_power_treads = true,
	item_angel_wings = true,
	item_quelling_fury = true,
	item_linken_sphere = true,

	item_yasha = true,
	item_sange = true,
	item_sange_and_yasha = true,
	item_sange_and_yasha_and_kaya = true,
	item_monkey_king_bar = true,
	item_demon_king_bar = true,
	item_echo_sabre_arena = true,
	item_echo_sabre_2 = true,
	item_lifesteal = true,
	item_mask_of_madness = true,
	item_golden_eagle_relic = true,
	item_desolator3 = true,
	item_desolator4 = true,
	item_desolator5 = true,
	item_desolator6 = true,
	item_skull_of_midas = true,
	item_butterfly_arena  = true,
	item_butterfly_of_wind  = true,
	item_timelords_butterfly  = true,

}
